version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
    branches:
      only:
        - main
    steps:
      - add_ssh_keys:
          fingerprints:
            - "bd:a6:a4:0b:b5:71:be:69:5d:f9:b0:16:ef:69:b6:de"
      - checkout
      - run: echo 'A first Hello'
      - run:
          name: Install
          command: npm install
      - run:
          name: Build
          command: npm run build